### ISSUE TITLE
[Android][0.74.5] 0.3.9 Attempt to invoke interface method on a null object reference

### ISSUE THREAD

**Issue by SteveHoneckPGE** [ArturKalach/react-native-external-keyboard#45] opened 2024-10-01 13:49 UTC
On version 0.3.9 (react native 0.74.5), when removing the screen that has <KeyboardExtendedInput> from the navigation stack , I get the following error on Android:

> Attempt to invoke interface method 'void android.view.View$onAttachStateChangeListener.onViewDetachedFromWindow(android.view.View)' on a null object reference

<img src="https://github.com/user-attachments/assets/5e85b988-ac94-40b4-96d6-dc4118d12797" width="200">

The same implementation of <KeyboardExtendedInput> 0.3.8 did not have this issue. 0.3.7 also does not have the issue (we rolled back the application to 0.3.7 for now).
Time allowing, I can add more information about the issue if needed.

@ArturKalach, also, I want to thank you for 'react-native-external-keyboard' and 'react-native-is-keyboard-connected'. Our application is required to conform to WCAG, and those two libraries made compliance possible.

**Comment by ArturKalach** [comment] 2024-10-01 20:39
Hello @SteveHoneckPGE 

Thank you for reporting the issue; I really appreciate it.

I have implemented a fix, but I haven't had time to reproduce and verify it with a real example. I will try to do that tomorrow and publish a new version.
In the meantime, you can test the issue with `0.3.10-rc` and share the results, whether it is fixed or not.


If I’m not mistaken, the issue was due to an incorrect approach to removing the listener. Instead of removing it, I set it to null.



___
P.S. Thank you for your kind words! I understand how challenging it can be to support WCAG requirements. The foundation of this library comes from efforts to comply with WCAG guidelines, which has since become my hobby.

FYI, I am preparing a significant update that includes a HOC, focus, auto-focus, and an improved highlight system. You can check it out [here](https://github.com/ArturKalach/react-native-external-keyboard/tree/release/0.4.0-alpha0). I believe this update could be really useful and represent the next step in enhancing accessibility (A11y) and keyboard navigation support.

**Comment by SteveHoneckPGE** [comment] 2024-10-02 15:38
I tested with 0.3.10-rc and the error is no longer happening.
All other use-cases for our specific implementation are still working as expected as well. 

Thank you for addressing it so quickly!

**Comment by ArturKalach** [comment] 2024-10-02 17:45
Hello @SteveHoneckPGE,

Yes, I have also verified and reproduced the crash.
To resolve this, a new version has been published. You can now use version 0.3.10.

**Comment by ArturKalach** [comment] 2024-10-07 11:21
The issue has been resolved with `0.3.10`.

**Closed by ArturKalach** 2024-10-07 11:21 UTC
